INSERT INTO MPA (ID,NAME)
SELECT ID,NAME FROM (
    SELECT 1 AS ID,'G' AS NAME union
    SELECT 2 AS ID,'PG' AS NAME union
    SELECT 3 AS ID,'PG-13' AS NAME union
    SELECT 4 AS ID,'R' AS NAME union
    SELECT 5 AS ID,'NC-17' AS NAME
) AS x WHERE NOT EXISTS (SELECT * FROM MPA WHERE MPA.ID=ID);


INSERT INTO GENRES (ID,NAME)
SELECT ID,NAME FROM (
SELECT 1 AS ID,'Комедия' AS NAME union
SELECT 2 AS ID,'Драма' AS NAME union
SELECT 3 AS ID,'Мультфильм' AS NAME union
SELECT 4 AS ID,'Триллер' AS NAME union
SELECT 5 AS ID,'Документальный' AS NAME union
SELECT 6 AS ID,'Боевик' AS NAME
) AS x WHERE NOT EXISTS (SELECT * FROM GENRES WHERE GENRES.ID=ID);