CREATE TABLE IF NOT EXISTS MPA (
                                   id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    name VARCHAR);

CREATE TABLE IF NOT EXISTS GENRES (
                                     id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     name VARCHAR);

CREATE TABLE IF NOT EXISTS FILMS (
                                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    name varchar(255) NOT NULL,
                                    description varchar(200),
                                    releasedate date NOT NULL,
                                    duration BIGINT NOT NULL,
                                    mpa_id INT REFERENCES mpa(id) NOT NULL);

CREATE TABLE IF NOT EXISTS FILM_GENRE (
                                          id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          genre_id integer REFERENCES genres (id) ON DELETE CASCADE NOT NULL,
                                          film_id integer REFERENCES films (id) ON DELETE CASCADE NOT NULL);

CREATE TABLE IF NOT EXISTS USERS (
                                     id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     name varchar,
                                     login varchar NOT NULL,
                                     email varchar NOT NULL,
                                     birthday date NOT NULL);

CREATE TABLE IF NOT EXISTS FRIENDS (
                                      id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      user_id integer REFERENCES users (id) ON DELETE CASCADE NOT NULL,
                                      friend_id integer REFERENCES users (id) ON DELETE CASCADE NOT NULL);


CREATE TABLE IF NOT EXISTS FILM_LIKES (
                                              id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                              film_id integer REFERENCES films (id) ON DELETE CASCADE NOT NULL,
                                              user_id integer REFERENCES users (id) ON DELETE CASCADE NOT NULL);

CREATE TABLE IF NOT EXISTS REVIEWS
(
    id   INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id     INT REFERENCES USERS ON DELETE CASCADE NOT NULL,
    film_id     INT REFERENCES FILMS ON DELETE CASCADE  NOT NULL,
    is_positive BOOLEAN                                NOT NULL,
    useful      INT                                    NOT NULL,
    content     VARCHAR(128)
);
CREATE UNIQUE INDEX IF NOT EXISTS reviews_uq_user_film on REVIEWS (user_id, film_id);